version = 1

test_patterns = [
  "**/*.test.tsx",
  "**/*.test.ts"
]

exclude_patterns = ["example/*"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser", "jest", "nodejs"]

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
